apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sftp-deployment
  labels:
    app: sftp
spec:
  selector:
    matchLabels:
      app: sftp
  template:
    metadata:
      labels:
        app: sftp
    spec:
      containers:
      - image: atmoz/sftp
        args: ["foo:pass:1001:0:/upload"]
        name: aftp
        volumeMounts:
        - name: task-pv-storage
          mountPath: "/home/foo/upload"
      volumes:
      - name: task-pv-storage
        persistentVolumeClaim:
          claimName: cospvc